app:
  datasource:
    jdbc-url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME} # PostgreSQL username
    password: ${SPRING_DATASOURCE_PASSWORD} # PostgreSQL password
    pool-size: 30
  upload:
    dir: ${user.home}/nodecode_uploads
spring:
  flyway:
    baseline-on-migrate: true
  security:
    oauth2:
      client:
        registration:
          github:
            clientId: ${SPRING_GITHUB_CLIENT_ID}
            clientSecret: ${SPRING_GITHUB_CLIENT_SECRET}
            redirectUri: "http://localhost/api/v1/oauth2/callback/github"
            scope:
              - user:email
              - read:user
  application:
    name: Nodecode Production Server
  banner:
    location: classpath:static/banner-prod.txt
